site_name: TorchJune
site_url: https://arnauqb.github.io/torch_june/
nav:
  - Home: index.md
  - Quickstart: quickstart.md
theme: readthedocs
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

